# Copyright © 2020 Cask Data, Inc.
#  Licensed under the Apache License, Version 2.0 (the "License"); you may not
#  use this file except in compliance with the License. You may obtain a copy of
#  the License at
#  http://www.apache.org/licenses/LICENSE-2.0
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations under
#  the License.

# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache
      uses: actions/cache@v2.1.3
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: ${{ env.HOME }}/.m2
        # An explicit key for restoring and saving the cache
        key: Local Maven Repository
    - name: Build with Maven
      run: mvn clean test -fae -B -V -P templates,skip-hbase-compat-tests -Dmaven.wagon.http.retryHandler.count=3
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: rat report
        path: target/rat.txt
    - name: Surefire Report
      uses: ScaCap/action-surefire-report@v1.0.5
      if: always()
      with:
        # GITHUB_TOKEN
        github_token: ${{ secrets.GITHUB_TOKEN }}
    
